version: '3.4'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  centrifugo:
    image: centrifugo/centrifugo
    command: centrifugo --config=config.json --admin --redis_host=redis --log_level=debug
    volumes:
      - './deploy/centrifugo-config.json:/centrifugo/config.json'
    ports:
      - '8000:8000'
